spring:
  application:
    name: integracion-bci
  datasource:
    url: jdbc:h2:file:./data/demo;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

user:
  password:
    regex: '^(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{8,}$'
  email:
    regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

app:
  secret: "12345678912345678912345678912345678912345678912345678912345678912345689"
  jwt:
    access-token:
      expiration: 3_600_000 # 1 hora en milisegundos