CREATE TABLE refresh_token (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    token VARCHAR NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);